# Image Representation

* Pixels
* Channels
* Images
* Dimensions
* height
* width

In [9]:
# Importing OpenCV
import cv2 as cv
import numpy as np

In [4]:
# A function that takes image as input to scale the image
def rescale(img, scale_factor = 0.5):
    
    height = int(img.shape[0]*scale_factor)
    width = int(img.shape[1]*scale_factor)

    return cv.resize(img,(width,height), interpolation=cv.INTER_AREA)

In [5]:
img = cv.imread("./../asserts/luffy.png", cv.IMREAD_COLOR)
while True:
    cv.imshow("Image", rescale(img, 0.3))
    if cv.waitKey(1) == ord('q'):
        break
cv.destroyAllWindows()
cv.imwrite("./../asserts/luffy_small.png",rescale(img,0.3))

True

In [6]:
print("Image Resolution : ",img.shape[:2])
print("Number of Channels : ",img.shape[-1])

Image Resolution :  (1800, 3200)
Number of Channels :  3


In [7]:
print("Image: ")
print(img)

Image: 
[[[ 40   4  34]
  [ 40   4  34]
  [ 40   4  34]
  ...
  [ 59  25   1]
  [ 59  25   1]
  [ 59  25   1]]

 [[ 40   4  34]
  [ 40   4  34]
  [ 40   4  34]
  ...
  [ 59  25   1]
  [ 59  25   1]
  [ 59  25   1]]

 [[ 40   4  34]
  [ 40   4  34]
  [ 40   4  34]
  ...
  [ 58  24   0]
  [ 58  24   0]
  [ 58  24   0]]

 ...

 [[ 50   1 115]
  [ 51   2 116]
  [ 51   2 116]
  ...
  [ 46  49   0]
  [ 46  49   0]
  [ 46  49   0]]

 [[ 50   1 115]
  [ 50   1 115]
  [ 51   2 116]
  ...
  [ 46  49   0]
  [ 46  49   0]
  [ 46  49   0]]

 [[ 50   1 117]
  [ 50   1 115]
  [ 51   2 116]
  ...
  [ 48  48   0]
  [ 48  48   0]
  [ 48  48   0]]]


In [8]:
img = cv.imread("./../asserts/luffy_small.png", cv.IMREAD_COLOR)

while True:
    cv.imshow("Image", img)
    cv.imshow("blue", img[:,:,0])
    cv.imshow("green", img[:,:,1])
    cv.imshow("red", img[:,:,2])
    if cv.waitKey(1) == ord('q'):
        break
cv.destroyAllWindows()

In [24]:
w = 120
h=120
img = np.zeros(w*h*3).reshape((w,h,3))

img[:w//3,:,0] = 255
img[w//3:2*w//3,:,1] = 255
img[2*w//3:,:,2] = 255

while True:
    cv.imshow("Image", img)
    cv.imshow("blue", img[:,:,0])
    cv.imshow("green", img[:,:,1])
    cv.imshow("red", img[:,:,2])
    if cv.waitKey(1) == ord('q'):
        break
cv.destroyAllWindows()

In [17]:
cv.destroyAllWindows()